### PR TITLE
Fix TypeError in verify-attached-bugs

### PR DESCRIPTION
**Pull request by vfreex**
Got the following error:
```
TypeError: categorize_bugs_by_type() missing 1 required positional argument: 'permitted_bug_ids'
```

The bug was introduced by https://github.com/openshift-eng/art-tools/commit/9f3b49306db5eb7af1614244614300d848747099

### CODE REVIEW

**Review by locriandev — COMMENTED** [review]
/lgtm

**Review by locriandev — COMMENTED** [review]
/lgtm
